language: cpp
compiler:
  - clang

before_install:
  - mkdir -p _build
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
  - sudo apt-get update

install:
  - sudo apt-get install -y cmake
  - cmake --version

script:
  - cd _build
  - cmake ..
  - cmake --build .


