
# inspired by
#     some googling
#     llvm.org/apt
#     docs.travis-ci.com and github.com/beark/ftl/blob/master/.travis.yml
#     stackoverflow.com/a/30925448/865719
#     docs.travis-ci.com/user/apt

# run this in a container
sudo: false
language: cpp
compiler:
  - clang
  - gcc

env:
  - BUILD_TYPE=Debug
  - BUILD_TYPE=Release

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - clang-3.6
      - lldb-3.6
      - libc++-dev

before_install:
  # install g++
  - if [ "$CXX" = "g++" ]; then g++-4.8 --version; fi
  - if [ "$CXX" = "g++" ]; then gcc-4.8 --version; fi
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8"; fi
  - if [ "$CXX" = "g++" ]; then export CC="gcc-4.8"; fi

  # install clang
  - if [ "$CXX" = "clang++" ]; then clang++-3.6 --version; fi
  - if [ "$CXX" = "clang++" ]; then clang-3.6 --version; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-3.6"; fi
  - if [ "$CXX" = "clang++" ]; then export CC="clang-3.6"; fi

install:
  # cmake 3
  - mkdir -p _build/cmake_bin _build/cmake_build
  - wget --no-check-certificate https://cmake.org/files/v3.3/cmake-3.3.2-Linux-x86_64.tar.gz -O _build/cmake_bin/cmake.tgz
  - tar xvfz _build/cmake_bin/cmake.tgz -C _build/cmake_bin
  - export CMAKE3="$(pwd)/_build/cmake_bin/cmake-3.3.2-Linux-x86_64/bin/cmake"

script:
  - cd _build/cmake_build
  - $CMAKE3 -DCMAKE_BUILD_TYPE=$BUILD_TYPE ../..
  - $CMAKE3 --build .



