
environment:
  matrix:
    - GENERATOR: "Visual Studio 14"
      BUILD_TYPE: Debug

    - GENERATOR: "Visual Studio 14"
      BUILD_TYPE: Release

    - GENERATOR: "Visual Studio 14 Win64"
      BUILD_TYPE: Debug

    - GENERATOR: "Visual Studio 14 Win64"
      BUILD_TYPE: Release

build_script:
  - mkdir _build
  - cd _build
  - cmake "-G%GENERATOR%" ..
  - cmake --build . --config "%CONFIG%"
