
environment:
  matrix:
    - GENERATOR: "Visual Studio 14"
      CONFIG: Debug

    - GENERATOR: "Visual Studio 14"
      CONFIG: Release

    - GENERATOR: "Visual Studio 14 Win64"
      CONFIG: Debug

    - GENERATOR: "Visual Studio 14 Win64"
      CONFIG: Release

build_script:
  - mkdir _build
  - cd _build
  - cmake "-G%GENERATOR%" "-DCMAKE_BUILD_TYPE=%BUILD_TYPE%" ..
  - cmake --build .
